config/routes.rb
Rails.application.routes.draw do
  get "/projects/destroy_all", to: "projects#destroy_all", as: :destroy_all
  resources :projects
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    project = Project.create(project_params(:title, :description))
    redirect_to project_path(project)
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    project = Project.find(params[:id])
    project.update(project_params(:title, :description))
    redirect_to project_path(project)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  def destroy_all
    Project.destroy_all
    redirect_to projects_path
  end

  private

  def project_params(*args)
    params.require(:project).permit(*args)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kickstarter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<%= form_for @project do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <%= f.submit %>
<%end%>

app/views/projects/index.html.erb
<% @projects.each do |p| %>
<div><%= link_to p.title, project_path(p) %></div>
<div><%= p.description %></div>
<% end %><br>
<p><%= link_to "Create New", new_project_path %></p>
<p><%= link_to "Delete All", destroy_all_path, data: { confirm: 'Are you sure?'} %></p>

app/views/projects/new.html.erb
<%= form_for @project do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <%= f.submit %>
<%end%>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<p><%=@project.description%></p>
<p><%= link_to "Index", projects_path %></p>
<p><%= link_to "Edit", edit_project_path(@project) %></p>
<p><%= link_to "Delete", @project, method: :delete,  data: { confirm: 'Are you sure?'} %></p>